global:
  scrape_interval: 5s  # Scrape every 5 seconds

scrape_configs:
  - job_name: 'cart-service'
    metrics_path: '/actuator/prometheus' 
    static_configs:
      - targets: ['ecom-cart-service:8113']