apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spring-ms-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: myapp.local
      http:
        paths:
          - path: /product-service(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: ecom-product-service
                port:
                  number: 8112

          - path: /user-service(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: ecom-user-service
                port:
                  number: 8111

          - path: /cart-service(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: ecom-cart-service
                port:
                  number: 8113
        
